---
- name: Provision EC2 Instances
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 Instances
      ec2:
        key_name: ansible_controller
        instance_type: t2.micro
        image: ami-0efcece6bed30fd98  # Specify the correct Ubuntu AMI ID
        wait: yes
        count: 4
        region: us-west-2
        group: launch-wizard-5
        vpc_subnet_id: subnet-008b9052f9d7693a3
        assign_public_ip: yes
        instance_tags:
          Environment: my_env
      register: ec2_instances

    - name: Debug ec2_instances
      debug:
        var: ec2_instances

    - name: Add EC2 instances to dynamic inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ec2_instances
      with_items: "{{ ec2_instances.instances }}"

    - name: Debug dynamic inventory
      debug:
        var: hostvars
